### ISSUE TITLE
Some issue

### ISSUE THREAD

**Issue by simonyipeter** [Mjrovai/OpenCV-Object-Face-Tracking#1]
Hi, 

This code is awesome!
I added some feature: MySQL, Web interface and I planning to merge the Data Gathering and the Recognize processes.

But I found some bug:
RPI3, Python 3 and OpenCV 3.3

1. There are no cv2.face.LBPHFaceRecognizer_create() function
I modified:
recognizer = cv2.face.createLBPHFaceRecognizer()

2. There are no write() only the save() function:
recognizer.save('trainer/trainer.yml') # recognizer.save() worked on Mac, but not on Pi

3. The predict function gives back only one variable, the id:
id = recognizer.predict(gray[y:y+h,x:x+w])

**Comment by Mjrovai** [comment]
Hi,
Thanks a lot! Please share your project with the community. Would be great!  
Regarding your "Bug findings", I suppose that should be something with your OpenCV installation:
1. cv2.face.LBPHFaceRecognizer_create() function works fine for me, both on Raspberry Pi and Mac
2. Yes, you must change it depending your computer (on RPI is "write" and on Mac is "save")
3. id, confidence = recognizer.predict(gray[y:y+h,x:x+w]) returns 2 variables, "id" and "confidence".

**Comment by simonyipeter** [comment]
Sorry, It's my fault, I used OpenCV 3.1

2018-03-04 21:37 GMT+01:00 Marcelo Rovai <notifications@github.com>:
