### ISSUE TITLE
Importing cv2

### ISSUE THREAD

**Issue by ghost** [Mjrovai/OpenCV-Object-Face-Tracking#2]
Hi.
I really love the project and i'm using it as a template for a school project. I only have one problem that keeps occurring and it's when i try to import cv2. I'm doing all the programming on a Raspberry Pi 3 Model B with Rasbian installed. I can import the cv2 in the normal python IDLE, in the terminal. Can't get it to work with any IDE Editors though, only gets the error "ImportError: No module named cv2". Even when i try running the simpleCamTest.py i get the same error. If i type the code manually the import works but i get a new error.

"OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /home/pi/opencv-3.3.0/modules/imgproc/src/color.cpp, line 10638
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
cv2.error: /home/pi/opencv-3.3.0/modules/imgproc/src/color.cpp:10638: error: (-215) scn == 3 || scn == 4 in function cvtColor"

Was really hoping to get the project going, but can't really get anywhere when even the template itself isn't working :D 
Thanks in advance

**Comment by Mjrovai** [comment]
Hi. Yes it is correct. You need the Special environment to run OpenCV. Outside of it, the OS does not recognize it. You could install OpenCV directly on your system, but the experts do not recommend it. 
I use IDE to create, test, modify etc the code, but usually run them on terminal. You can always create a final executable file if necessary.

**Comment by ghost** [comment]
When you talk about the Special environment i would presume that you are talking about the "workon cv" command to enter the virtual environment or is that two different things. If it is the virtual environment then i did try to run the code in the environment through the terminal, but got the same error. Do you know of a way to open or access the virtual environment with an IDE outside of the terminal. And do you have any recommendations of IDE's?

**Comment by Mjrovai** [comment]
Yes, the python virtual environment. It is important to run the command "source" each time you open a new terminal to ensure your system variables have been set up correctly.
source ~/.profile
After the command source, enter on your virtual environment with:
workon cv

After you install OpenCV for the first time, did you check on the terminal, inside Virtual Environment (VE), if "import cv2" worked on python shell? If did not work, something should be wrong with your installation.

I do not know to work with an IDE outside the VE, when you have the OpenCV installed on VE.

On RPI 3, with simple projects (Python only) usually I work with Thonny. In case of OpenCV projects (and also with Flask), I like Geany, because inclusive you can use the integrate terminal at bothon of the IDE.

**Comment by ghost** [comment]
I have used the "source ~/.profile" command everytime I opened the terminal and continued with "workon cv". 
The "import cv2" command does work inside the python shell, and the import is successful. As mentioned above, when I successfully import cv2 and run the rest of the script inside the VE i get the following error:

"OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /home/pi/opencv-3.3.0/modules/imgproc/src/color.cpp, line 10638
Traceback (most recent call last):
File "", line 5, in
cv2.error: /home/pi/opencv-3.3.0/modules/imgproc/src/color.cpp:10638: error: (-215) scn == 3 || scn == 4 in function cvtColor"

Could the problem be with how I apply the script inside of the shell, like how I copy and paste the script itself? I am new to programming inside of shells, and have always used custom IDE's like VSC and Eclipse (on Windows PC). So, there could be something there.

How do I go into the VE when I want to run the script. That could be the error. I did as following: 
- Opened the terminal
- command "source ~/.profile"
- command "workon cv"
- command "python simpleCamTest.py"
The output is the error message: "ImportError: No module named cv2"

Sorry for all the questions, i'm kinda lost here :D

**Comment by ghost** [comment]
I did also try the IDE's Thonny and Geany with the script (simpleCamTest.py) and manually writing the code, got the same error: "ImportError: No module named cv2"

**Comment by Mjrovai** [comment]
Seems that OpenCV is not correctly installed.

**Comment by RoyamShafiq** [comment]
What is this suppose to be sir? HELP ME

Traceback (most recent call last):
  File "/home/pi/trial.py", line 83, in <module>
    frame = imutils.resize(frame,width=500)
  File "/usr/local/lib/python2.7/dist-packages/imutils/convenience.py", line 69, in resize
    (h, w) = image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by RoyamShafiq** [comment]
this happens just after camera warmup message...
